### ISSUE TITLE
Return variable of function "featurization" in features.py

### ISSUE THREAD

**Issue by qle2** [Dlux804/McQuade-Chem-ML#13]
@Dlux804 I noticed that you change one of the return variable in the function featurization in features.py from selected_feat to num_feat. Is there a reason for that change?

![image](https://user-images.githubusercontent.com/56049656/69680773-ed819080-1079-11ea-8706-4a9b09f74e83.png)

I'm asking this because one of my test depends on that variable to be a list of strings (selected_feat) instead of list of numbers (num_feat). I have tested models.py when the return variable is selected_feat and it works just fine.

Do you mind if we switch variable from num_feat to selected_feat?

**Comment by qle2** [comment]
@Dlux804 One of the goal of my testing script for features.py is to see if it can drop the 'rdkit2d' column in the right circumstances. So I needed the actual string to see if 'rdkit2d' is still there. But I think I can figure out a way to work around it.

**Comment by Dlux804** [comment]
@qle2 Has this been resolved?  We discussed it in person I believe.  If it is resolved, please close.  If not, please explain what extra info you need.

**Comment by qle2** [comment]
I believe everything has been resolved.
Thanks for the reminder.
