### ISSUE TITLE
Increase feature generation speed in features.py

### ISSUE THREAD

**Issue by qle2** [Dlux804/McQuade-Chem-ML#21]
**Is your feature request related to a problem? Please describe.**
The original piece of code is not a problem. Just a more efficient way to store things in a list.
![image](https://user-images.githubusercontent.com/56049656/72617702-97a5c800-3907-11ea-8fe6-2bb33c0a9ad8.png)

**Describe alternatives you've considered**
![image](https://user-images.githubusercontent.com/56049656/72617795-c328b280-3907-11ea-8c86-128e0c5e5071.png)

**Comment by Dlux804** [comment]
@qle2 I am a bit confused.  Is this an issue?  It seems like you have a solution ready to go.  Just add it to your #22 and commit/push. (Don't forget to edit your pull request to mention this issue). It can go into effect through that once the review is finished.

**Comment by qle2** [comment]
Closes #22 .
