### ISSUE TITLE
Naming Scheme

### ISSUE THREAD

**Issue by qle2** [Dlux804/McQuade-Chem-ML#30]
**Is your feature request related to a problem? Please describe.**
Our current naming scheme for machine learning result is: dataset-algorithm-feature_number-tune, for example: water-energy-ada-0-tuned. While intuitive, it is too long for practical usage.

**Describe the solution you'd like**
A better naming scheme that is short, concise and follow a specific set of rules.

**Comment by Dlux804** [comment]
@qle2 Please address featurization naming in this ticket as well.  i.e `[0,2]` can be improved.

**Comment by qle2** [comment]
Done in Pull Request #47
