### ISSUE TITLE
sklearn Callbacks

### ISSUE THREAD

**Issue by qle2** [Dlux804/McQuade-Chem-ML#32]
**Is your feature request related to a problem? Please describe.**
Right now, we don't have callbacks implemented into our machine learning workflow. Callbacks are essential as it gives us more information and control over the training process.

**Describe the solution you'd like**
Create callbacks and add it into the Bayesian Optimization. 

**Describe alternatives you've considered**
Figure out a way to use skopt's callback functions 

**Additional context**
https://www.kdnuggets.com/2019/08/keras-callbacks-explained-three-minutes.html
https://scikit-optimize.github.io/stable/modules/classes.html#module-skopt.callbacks

**Comment by Dlux804** [comment]
Changed name to disambiguate from callbacks used in Tensorflow, which will have its own ticket.
