### ISSUE TITLE
Update Documentations

### ISSUE THREAD

**Issue by qle2** [Dlux804/McQuade-Chem-ML#33]
**Is your feature request related to a problem? Please describe.**
We lack instructions or documentations on more recent work such as Neo4j related projects or new additions to the machine learning workflows.

**Describe the solution you'd like**
Add doc strings. Update README.md. Update Neo4j's overleaf document.

**Additional context**
https://github.com/Dlux804/McQuade-Chem-ML/blob/master/README.md

**Comment by andreshyer** [comment]
I know it has been almost a month since you opened this issue Quang, but I am going to start working on adding documentation to the Andres-Neo4j branch.
