### ISSUE TITLE
Save Sklearn Machine Learning Results

### ISSUE THREAD

**Issue by qle2** [Dlux804/McQuade-Chem-ML#34]
**Is your feature request related to a problem? Please describe.**
The current sklearn machine learning workflow doesn't save machine learning models besides outputs such as scores and graphs. 

**Describe the solution you'd like**
Add a way to save and load machine learning models using Pickle or joblib. 

**Additional context**
https://machinelearningmastery.com/save-load-machine-learning-models-python-scikit-learn/

**Comment by qle2** [comment]
Done in Pull Request #47

**Comment by Dlux804** [comment]
I argue that this is not yet closed.  You have implemented saving the models via pkl files output by the Bayesian optimizer, but I do not recall a method for loading models in your last PR.  Additional question -- what is being saved in the pkl file from Bayes?  At that point, I am not sure we have our final model yet.  We receive from the Bayes optimizer the optimal parameters, but I believe we need to retrain the model with those parameters (they were not necessarily the last ones used in the Bayes algorithm.)
