### ISSUE TITLE
Adding sklearn Classification Models

### ISSUE THREAD

**Issue by dickeygh** [Dlux804/McQuade-Chem-ML#35]
**Is your feature request related to a problem? Please describe.**
Our models only use regression algorithms, not classification algorithms. My goal is to add classification algorithms to our models.

**Describe the solution you'd like**
Add classification methods to our programs in order to make them more useful/encompassing.

**Describe alternatives you've considered**
There are different potential classification algorithms that could be used, including K-Nearest Neighbors, Support Vector Machines, Decision Tree Classifiers/Random Forests, Naive Bayes, Linear Discriminant Analysis, and Logistic Regression.

**Additional context**
https://stackabuse.com/overview-of-classification-methods-in-python-with-scikit-learn/
http://moleculenet.ai/datasets-1

**Comment by Dlux804** [comment]
Good.  You may want to consider breaking this into smaller chunks in multiple issues.  Up to you @dickeygh
