### ISSUE TITLE
Cypher Code for Prototype Knowledge Graph

### ISSUE THREAD

**Issue by Dlux804** [Dlux804/McQuade-Chem-ML#38]
**Describe the solution you'd like**
A text file in the repo containing Cypher commands for creating a small prototype knowledge graph.  Easily editable for quick adjustments as we explore ontology possibilities.  

Additionally, a similar file for the markdown to create the ontology in the Arrow Tool.  This is just copy and pasted from the online tool.  

**Describe alternatives you've considered**

**Additional context**
[Online Ontology Arrow Tool](http://www.apcjones.com/arrows/#)

**Comment by qle2** [comment]
@Dlux804 Do you think we should both work on the same branch for these text files?

**Comment by Dlux804** [comment]
I think its not super important since it is just a text file.

**Comment by Dlux804** [comment]
Since it doesn't really interact with anything in the code, that is.
