### ISSUE TITLE
Add hyperparameter tuning to the classification pipeline.

### ISSUE THREAD

**Issue by dickeygh** [Dlux804/McQuade-Chem-ML#50]
**Is your feature request related to a problem? Please describe.**
Now that I have added a basic classification pipeline to our code base, I would like to begin researching adding classification hyperparameter tuning to the classification pipeline. This would increase the sophistication/robustness of the classification models. 

**Describe the solution you'd like**
I would like to add some sort of hyperparameterization method to the classification pipeline so that the models can make stronger/more useful predictions.

**Comment by Dlux804** [comment]
@dickeygh 
 **Just a heads up:**  I don't think that there will be much different in terms of hyper parameter tuning for classification.  A few details will need to be tuned, such as what is the scoring function.  I am working on hooking the classifiers up to the tuning algorithm, and noticed the scoring function (RMSE) is not applicable to classification.   So don't work on this beyond the scoring function for `BayesSearchCV` for now.
