### ISSUE TITLE
Moleculenet classification data sets not working properly. 

### ISSUE THREAD

**Issue by dickeygh** [Dlux804/McQuade-Chem-ML#60]
**Describe the bug**
`TypeError: object of type 'NoneType' has no len() `error message is returned at line 56 `features = pd.DataFrame(data, columns=columns)` when trying to use both the clintox data set and the BBBP data set. 

`ValueError: Shape of passed values is (2, 1), indices imply (2, 201)` error message is returned at line 56 `features = pd.DataFrame(data, columns=columns)` when trying to use both the HIV data set and the bace data set.

**To Reproduce**
1. Checkout the Feature_G branch from Github
2. Run the different data sets by changing line 29 in `main.py
`
3. Running these data sets should reproduce the error.

**Expected behavior**
These 4 data sets should be able to run successfully, similarly to the sider data set. 

**Screenshots**
![Clintox error message](https://user-images.githubusercontent.com/62520394/86160480-cb516480-bad9-11ea-9999-28967b37fdb3.PNG)
![BBBP error message](https://user-images.githubusercontent.com/62520394/86160491-d0161880-bad9-11ea-8c53-5e7e94866b95.PNG)
![HIV error message](https://user-images.githubusercontent.com/62520394/86160502-d3a99f80-bad9-11ea-8e57-7328655ba460.PNG)
![bace error message](https://user-images.githubusercontent.com/62520394/86160504-d4dacc80-bad9-11ea-9793-fea532cd3920.PNG)

**Desktop (please complete the following information):**
 - OS: Windows

**Other notes**
The error message seems to appear regardless of featurization option selected or model selected.

**Comment by qle2** [comment]
Fixed in PR #70
